#!/usr/bin/env ruby -wKU

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# 
# Find the sum of all the even-valued terms in the sequence which do not exceed four million.

def fibonacci( m, n, finish )
  unless (a = m + n) > finish
    sum = (a % 2 == 0 ? a : 0) + fibonacci( n, a, finish )
  else
    sum = 0
  end
end

answer = fibonacci 0, 1, 4_000_000
puts "answer: #{answer}"

def fib( m, n, finish )
  (a = m + n) > finish ? 0 : (a % 2 == 0 ? a : 0) + fib( n, a, finish )
end

answer = fib 0, 1, 4_000_000
puts "answer: #{answer}"